spring:
  application:
    name: metalmod-core

  datasource:
    url: jdbc:postgresql://localhost:5432/metalmod_core
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Mme010$}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # 'validate' porque Flyway es quien manda en el esquema, no Hibernate
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

azure:
  tenant-id: "TU_TENANT_ID_DE_AZURE"
  client-id: "TU_CLIENT_ID_DE_LA_APP"
  client-secret: "TU_CLIENT_SECRET"

excel:
  file:
    item-id: "ID_DEL_ARCHIVO_EN_CLOUD"